# Generated by Django 5.2.8 on 2025-12-04 10:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The audit question text', verbose_name='Question')),
                ('possible_points', models.DecimalField(decimal_places=2, help_text='Maximum points achievable for this question', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Possible Points')),
                ('is_critical', models.BooleanField(default=False, help_text='Whether this is a critical question (zero score fails entire audit)', verbose_name='Critical?')),
                ('critical_failure_condition', models.TextField(blank=True, help_text='Description of what constitutes a critical failure', verbose_name='Critical Failure Condition')),
                ('order', models.IntegerField(default=0, help_text='Display order within section', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(help_text='Date when the audit was conducted', verbose_name='Audit Date')),
                ('manager_on_duty', models.CharField(help_text='Name of the manager present during audit', max_length=255, verbose_name='Manager On Duty')),
                ('auditor_signature', models.TextField(blank=True, help_text='Digital signature of the auditor', verbose_name='Auditor Signature')),
                ('auditee_signature', models.TextField(blank=True, help_text='Digital signature of the auditee', verbose_name='Auditee Signature')),
                ('total_scored', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Score')),
                ('total_possible', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Possible Score')),
                ('total_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Percentage')),
                ('grade', models.CharField(blank=True, choices=[('A', 'A (96.0 - 100)'), ('B', 'B (90.0 - 95.9)'), ('C', 'C (80.0 - 89.9)'), ('F', 'F (Less than 80)')], max_length=1, verbose_name='Grade')),
                ('has_critical_failure', models.BooleanField(default=False, verbose_name='Has Critical Failure?')),
                ('previous_audit_date', models.DateField(blank=True, null=True, verbose_name='Previous Audit Date')),
                ('previous_audit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Previous Audit Score')),
                ('previous_auditor', models.CharField(blank=True, max_length=255, verbose_name='Previous Auditor Name')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Audit Submitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('auditor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Scored Points')),
                ('possible_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Possible Points')),
                ('section_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Section Percentage')),
                ('has_critical_failure', models.BooleanField(default=False, verbose_name='Critical Failure?')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audit', verbose_name='Audit')),
            ],
            options={
                'verbose_name': 'Audit Section',
                'verbose_name_plural': 'Audit Sections',
            },
        ),
        migrations.CreateModel(
            name='AuditQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Scored Points')),
                ('comments', models.TextField(blank=True, help_text='Additional comments or observations', verbose_name='Comments')),
                ('needs_corrective_action', models.BooleanField(default=False, verbose_name='Needs Corrective Action?')),
                ('audit_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditsection', verbose_name='Audit Section')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question Response',
                'verbose_name_plural': 'Question Responses',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Unique identifier for the restaurant', max_length=50, unique=True, verbose_name='Restaurant Code')),
                ('name', models.CharField(help_text='Official name of the restaurant', max_length=255, verbose_name='Restaurant Name')),
                ('address', models.CharField(help_text='Street address of the restaurant', max_length=255, verbose_name='Address')),
                ('city', models.CharField(help_text='City where the restaurant is located', max_length=100, verbose_name='City')),
                ('country', models.CharField(default='Pakistan', help_text='Country where the restaurant is located', max_length=50, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city'], name='core_restau_city_bff963_idx'), models.Index(fields=['country'], name='core_restau_country_ca44e7_idx')],
            },
        ),
        migrations.AddField(
            model_name='audit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant', verbose_name='Restaurant'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the audit section', max_length=50, verbose_name='Section Name')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the section', verbose_name='Description')),
                ('order', models.IntegerField(default=0, help_text='Display order for sections', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['order'], name='core_sectio_order_3cbe58_idx')],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='auditsection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Section'),
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='Detailed description of the corrective action needed', verbose_name='Description')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10, verbose_name='Risk Level')),
                ('assigned_to', models.CharField(help_text='Person responsible for completing the action', max_length=255, verbose_name='Assigned To')),
                ('deadline', models.DateField(help_text='Target completion date', verbose_name='Deadline')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed?')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('comments', models.TextField(blank=True, help_text='Additional comments or progress notes', verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audit', verbose_name='Audit')),
                ('question_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditquestionresponse', verbose_name='Question Response')),
            ],
            options={
                'verbose_name': 'Corrective Action',
                'verbose_name_plural': 'Corrective Actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audit'], name='core_correc_audit_i_7e9ebd_idx'), models.Index(fields=['risk_level'], name='core_correc_risk_le_20ba95_idx'), models.Index(fields=['completed'], name='core_correc_complet_5bd521_idx'), models.Index(fields=['deadline'], name='core_correc_deadlin_af0f09_idx'), models.Index(fields=['created_at'], name='core_correc_created_171c57_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='auditquestionresponse',
            index=models.Index(fields=['audit_section', 'question'], name='core_auditq_audit_s_4103ef_idx'),
        ),
        migrations.AddIndex(
            model_name='auditquestionresponse',
            index=models.Index(fields=['needs_corrective_action'], name='core_auditq_needs_c_c921c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditquestionresponse',
            constraint=models.UniqueConstraint(fields=('audit_section', 'question'), name='unique_audit_section_question'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['restaurant', 'audit_date'], name='core_audit_restaur_115d36_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['auditor_name', 'audit_date'], name='core_audit_auditor_03082b_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['grade'], name='core_audit_grade_c6e841_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['is_submitted'], name='core_audit_is_subm_115bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['has_critical_failure'], name='core_audit_has_cri_be41a3_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['created_at'], name='core_audit_created_8aaf3e_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['submitted_at'], name='core_audit_submitt_135232_idx'),
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.CheckConstraint(condition=models.Q(('total_scored__gte', 0)), name='audit_total_scored_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.CheckConstraint(condition=models.Q(('total_possible__gte', 0)), name='audit_total_possible_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.CheckConstraint(condition=models.Q(('total_percentage__gte', 0)), name='audit_total_percentage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.CheckConstraint(condition=models.Q(('total_percentage__lte', 100)), name='audit_total_percentage_max_100'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section', 'order'], name='core_questi_section_bef20c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_critical'], name='core_questi_is_crit_6b5f02_idx'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('possible_points__gte', 0)), name='question_possible_points_non_negative'),
        ),
        migrations.AddIndex(
            model_name='auditsection',
            index=models.Index(fields=['audit', 'section'], name='core_audits_audit_i_642485_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsection',
            index=models.Index(fields=['has_critical_failure'], name='core_audits_has_cri_b9149c_idx'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.UniqueConstraint(fields=('audit', 'section'), name='unique_audit_section'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.CheckConstraint(condition=models.Q(('scored_points__gte', 0)), name='auditsection_scored_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.CheckConstraint(condition=models.Q(('possible_points__gte', 0)), name='auditsection_possible_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.CheckConstraint(condition=models.Q(('section_percentage__gte', 0)), name='auditsection_percentage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.CheckConstraint(condition=models.Q(('section_percentage__lte', 100)), name='auditsection_percentage_max_100'),
        ),
    ]
