# Generated by Django 5.2.8 on 2025-11-13 07:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Audit Template')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Audit Template',
                'verbose_name_plural': 'Audit Templates',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Question')),
                ('possible_points', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Possible Points')),
                ('is_critical', models.BooleanField(default=False, verbose_name='Critical?')),
                ('critical_failure_condition', models.TextField(blank=True, verbose_name='Critical Failure Condition')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Restaurant Code')),
                ('name', models.CharField(max_length=255, verbose_name='Restaurant Name')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(default='Pakistan', max_length=50, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Section Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_date', models.DateField(verbose_name='Audit Date')),
                ('manager_on_duty', models.CharField(max_length=255, verbose_name='Manager On Duty')),
                ('auditor_signature', models.TextField(blank=True, verbose_name='Auditor Signature')),
                ('auditee_signature', models.TextField(blank=True, verbose_name='Auditee Signature')),
                ('total_scored', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Score')),
                ('total_possible', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Total Possible Score')),
                ('total_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Total Percentage')),
                ('grade', models.CharField(blank=True, choices=[('A', 'A (96.0 - 100)'), ('B', 'B (90.0 - 95.9)'), ('C', 'C (80.0 - 89.9)'), ('F', 'F (Less than 80)')], max_length=1, verbose_name='Grade')),
                ('previous_audit_date', models.DateField(blank=True, null=True, verbose_name='Previous Audit Date')),
                ('previous_audit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Previous Audit Score')),
                ('previous_auditor', models.CharField(blank=True, max_length=255, verbose_name='Previous Auditor Name')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Audit Completed')),
                ('is_submitted', models.BooleanField(default=False, verbose_name='Audit Submitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('auditor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='Auditor')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['-audit_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored_points', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Scored Points')),
                ('possible_points', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Possible Points')),
                ('section_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Section Percentage')),
                ('has_critical_failure', models.BooleanField(default=False, verbose_name='Critical Failure?')),
                ('is_completed', models.BooleanField(default=False)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audit', verbose_name='Audit')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Audit Section',
                'verbose_name_plural': 'Audit Sections',
                'ordering': ['audit', 'section'],
            },
        ),
        migrations.CreateModel(
            name='AuditQuestionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scored_points', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Scored Points')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('needs_corrective_action', models.BooleanField(default=False, verbose_name='Needs Corrective Action?')),
                ('audit_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditsection', verbose_name='Audit Section')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Question Response',
                'verbose_name_plural': 'Question Responses',
                'unique_together': {('audit_section', 'question')},
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10, verbose_name='Risk Level')),
                ('assigned_to', models.CharField(max_length=255, verbose_name='Assigned To')),
                ('deadline', models.DateField(verbose_name='Deadline')),
                ('completed', models.BooleanField(default=False, verbose_name='Completed?')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion Date')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audit', verbose_name='Audit')),
                ('question_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditquestionresponse', verbose_name='Question Response')),
            ],
            options={
                'verbose_name': 'Corrective Action',
                'verbose_name_plural': 'Corrective Actions',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Section'),
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audittemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='audittemplate',
            name='sections',
            field=models.ManyToManyField(through='core.TemplateSection', to='core.section'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['restaurant', 'audit_date'], name='core_audit_restaur_115d36_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['auditor_name', 'audit_date'], name='core_audit_auditor_03082b_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['grade'], name='core_audit_grade_c6e841_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['is_completed'], name='core_audit_is_comp_27555f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditsection',
            unique_together={('audit', 'section')},
        ),
    ]
