# Generated by Django 5.2.8 on 2025-11-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditsection',
            options={'ordering': ['audit', 'section'], 'verbose_name': 'Audit Section', 'verbose_name_plural': 'Audit Sections'},
        ),
    ]
