# Generated by Django 5.2.8 on 2025-11-13 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='audit',
            name='core_audit_is_comp_27555f_idx',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='auditsection',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='audit',
            name='has_critical_failure',
            field=models.BooleanField(default=False, verbose_name='Has Critical Failure?'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['is_submitted'], name='core_audit_is_subm_115bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['has_critical_failure'], name='core_audit_has_cri_be41a3_idx'),
        ),
    ]
