# Generated by Django 5.2.8 on 2025-11-13 11:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_audit_core_audit_is_comp_27555f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='possible_points',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Possible Points'),
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.CheckConstraint(condition=models.Q(('total_scored__gte', 0)), name='audit_total_scored_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.CheckConstraint(condition=models.Q(('total_possible__gte', 0)), name='audit_total_possible_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.CheckConstraint(condition=models.Q(('total_percentage__gte', 0)), name='audit_total_percentage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.CheckConstraint(condition=models.Q(('scored_points__gte', 0)), name='auditsection_scored_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.CheckConstraint(condition=models.Q(('possible_points__gte', 0)), name='auditsection_possible_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.CheckConstraint(condition=models.Q(('possible_points__gte', 0)), name='question_possible_points_non_negative'),
        ),
    ]
