# Generated by Django 5.2.8 on 2025-11-06 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_auditsection_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesection',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templatesection',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['-audit_date'], 'permissions': [('view_own_audit', 'Can view own audits only')], 'verbose_name': 'Audit', 'verbose_name_plural': 'Audits'},
        ),
        migrations.AlterModelOptions(
            name='auditsection',
            options={'ordering': ['section__order'], 'verbose_name': 'Audit Section', 'verbose_name_plural': 'Audit Sections'},
        ),
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Corrective Action', 'verbose_name_plural': 'Corrective Actions'},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='country',
        ),
        migrations.AddField(
            model_name='auditquestionresponse',
            name='evidence_photo',
            field=models.ImageField(blank=True, null=True, upload_to='audit_evidence/', verbose_name='Evidence Photo'),
        ),
        migrations.AddField(
            model_name='auditsection',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Section Comments'),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='action_taken',
            field=models.TextField(blank=True, verbose_name='Action Taken'),
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True, verbose_name='Help Text'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='auditor_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to=settings.AUTH_USER_MODEL, verbose_name='Auditor'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A (96.0 - 100)'), ('B', 'B (90.0 - 95.9)'), ('C', 'C (80.0 - 89.9)'), ('F', 'F (Less than 80)')], max_length=1, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='core.audit', verbose_name='Audit'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='question_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.auditquestionresponse', verbose_name='Question Response'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='risk_level',
            field=models.CharField(choices=[('LOW', "Low - Doesn't directly affect hygiene or food safety"), ('MEDIUM', 'Medium - Has the potential to affect hygiene or food safety'), ('HIGH', 'High - Presents an increased food safety risk'), ('CRITICAL', 'Critical - Unacceptable. Affects food safety')], max_length=10, verbose_name='Risk Level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Restaurant Code'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Section Name'),
        ),
        migrations.DeleteModel(
            name='AuditTemplate',
        ),
        migrations.DeleteModel(
            name='TemplateSection',
        ),
    ]
