# Generated by Django 5.2.8 on 2025-11-06 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_templatesection_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Audit Template')),
                ('version', models.CharField(default='1.0', max_length=50, verbose_name='Version')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
            ],
            options={
                'verbose_name': 'Audit Template',
                'verbose_name_plural': 'Audit Templates',
            },
        ),
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['-audit_date'], 'verbose_name': 'Audit', 'verbose_name_plural': 'Audits'},
        ),
        migrations.AlterModelOptions(
            name='auditsection',
            options={'ordering': ['audit', 'section'], 'verbose_name': 'Audit Section', 'verbose_name_plural': 'Audit Sections'},
        ),
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'verbose_name': 'Corrective Action', 'verbose_name_plural': 'Corrective Actions'},
        ),
        migrations.RemoveField(
            model_name='auditquestionresponse',
            name='evidence_photo',
        ),
        migrations.RemoveField(
            model_name='auditsection',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='correctiveaction',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='question',
            name='help_text',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_active',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='Pakistan', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audit', verbose_name='Audit'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='question_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditquestionresponse', verbose_name='Question Response'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10, verbose_name='Risk Level'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Section Name'),
        ),
        migrations.CreateModel(
            name='TemplateSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audittemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='audittemplate',
            name='sections',
            field=models.ManyToManyField(through='core.TemplateSection', to='core.section'),
        ),
    ]
