# Generated by Django 5.2.8 on 2025-11-24 17:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_question_possible_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audittemplate',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='templatesection',
            name='template',
        ),
        migrations.RemoveField(
            model_name='templatesection',
            name='section',
        ),
        migrations.AlterModelOptions(
            name='auditsection',
            options={'ordering': ['audit', 'section__order'], 'verbose_name': 'Audit Section', 'verbose_name_plural': 'Audit Sections'},
        ),
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Corrective Action', 'verbose_name_plural': 'Corrective Actions'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['audit_date'], name='core_audit_audit_d_e5f2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['risk_level'], name='core_correc_risk_le_20ba95_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['completed'], name='core_correc_complet_5bd521_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['deadline'], name='core_correc_deadlin_af0f09_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city'], name='core_restau_city_bff963_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['code'], name='core_restau_code_7b743e_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='core_restau_name_aa744f_idx'),
        ),
        migrations.DeleteModel(
            name='AuditTemplate',
        ),
        migrations.DeleteModel(
            name='TemplateSection',
        ),
    ]
