# Generated by Django 5.2.8 on 2025-11-10 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_audittemplate_alter_audit_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Completed At'),
        ),
        migrations.AddField(
            model_name='audit',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Audit Completed'),
        ),
        migrations.AddField(
            model_name='audit',
            name='is_submitted',
            field=models.BooleanField(default=False, verbose_name='Audit Submitted'),
        ),
        migrations.AddField(
            model_name='audit',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted At'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['restaurant', 'audit_date'], name='core_audit_restaur_115d36_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['auditor_name', 'audit_date'], name='core_audit_auditor_03082b_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['grade'], name='core_audit_grade_c6e841_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['is_completed'], name='core_audit_is_comp_27555f_idx'),
        ),
    ]
