# Generated by Django 5.2.8 on 2025-11-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_audittemplate_sections_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditsection',
            options={'ordering': ['audit', 'section'], 'verbose_name': 'Audit Section', 'verbose_name_plural': 'Audit Sections'},
        ),
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'verbose_name': 'Corrective Action', 'verbose_name_plural': 'Corrective Actions'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.RemoveIndex(
            model_name='audit',
            name='core_audit_audit_d_e5f2c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='correctiveaction',
            name='core_correc_risk_le_20ba95_idx',
        ),
        migrations.RemoveIndex(
            model_name='correctiveaction',
            name='core_correc_complet_5bd521_idx',
        ),
        migrations.RemoveIndex(
            model_name='correctiveaction',
            name='core_correc_deadlin_af0f09_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='core_restau_city_bff963_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='core_restau_code_7b743e_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='core_restau_name_aa744f_idx',
        ),
    ]
