# Generated by Django 5.2.8 on 2025-11-24 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_auditsection_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditsection',
            options={'ordering': ['audit', 'section__order'], 'verbose_name': 'Audit Section', 'verbose_name_plural': 'Audit Sections'},
        ),
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Corrective Action', 'verbose_name_plural': 'Corrective Actions'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active?'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='auditquestionresponse',
            name='audit_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditquestionresponse_set', to='core.auditsection', verbose_name='Audit Section'),
        ),
        migrations.AlterField(
            model_name='auditsection',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditsection_set', to='core.audit', verbose_name='Audit'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='core.audit', verbose_name='Audit'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='question_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='core.auditquestionresponse', verbose_name='Question Response'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.section', verbose_name='Section'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['audit_date'], name='core_audit_audit_d_e5f2c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditquestionresponse',
            index=models.Index(fields=['audit_section', 'question'], name='core_auditq_audit_s_4103ef_idx'),
        ),
        migrations.AddIndex(
            model_name='auditquestionresponse',
            index=models.Index(fields=['needs_corrective_action'], name='core_auditq_needs_c_c921c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsection',
            index=models.Index(fields=['audit', 'section'], name='core_audits_audit_i_642485_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['audit'], name='core_correc_audit_i_7e9ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['risk_level'], name='core_correc_risk_le_20ba95_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['completed'], name='core_correc_complet_5bd521_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['deadline'], name='core_correc_deadlin_af0f09_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['created_at'], name='core_correc_created_171c57_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section', 'order'], name='core_questi_section_bef20c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_critical'], name='core_questi_is_crit_6b5f02_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_active'], name='core_questi_is_acti_9c72ac_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city'], name='core_restau_city_bff963_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['code'], name='core_restau_code_7b743e_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='core_restau_name_aa744f_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['order'], name='core_sectio_order_3cbe58_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['is_active'], name='core_sectio_is_acti_1ee5af_idx'),
        ),
    ]
