# Generated by Django 5.2.8 on 2025-11-24 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_auditsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditsection',
            options={'ordering': ['audit', 'section'], 'verbose_name': 'Audit Section', 'verbose_name_plural': 'Audit Sections'},
        ),
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'verbose_name': 'Corrective Action', 'verbose_name_plural': 'Corrective Actions'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.RemoveIndex(
            model_name='audit',
            name='core_audit_audit_d_e5f2c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditquestionresponse',
            name='core_auditq_audit_s_4103ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditquestionresponse',
            name='core_auditq_needs_c_c921c3_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditsection',
            name='core_audits_audit_i_642485_idx',
        ),
        migrations.RemoveIndex(
            model_name='correctiveaction',
            name='core_correc_audit_i_7e9ebd_idx',
        ),
        migrations.RemoveIndex(
            model_name='correctiveaction',
            name='core_correc_risk_le_20ba95_idx',
        ),
        migrations.RemoveIndex(
            model_name='correctiveaction',
            name='core_correc_complet_5bd521_idx',
        ),
        migrations.RemoveIndex(
            model_name='correctiveaction',
            name='core_correc_deadlin_af0f09_idx',
        ),
        migrations.RemoveIndex(
            model_name='correctiveaction',
            name='core_correc_created_171c57_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='core_questi_section_bef20c_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='core_questi_is_crit_6b5f02_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='core_questi_is_acti_9c72ac_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='core_restau_city_bff963_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='core_restau_code_7b743e_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='core_restau_name_aa744f_idx',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='core_sectio_order_3cbe58_idx',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='core_sectio_is_acti_1ee5af_idx',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='audit',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='auditquestionresponse',
            name='audit_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditsection', verbose_name='Audit Section'),
        ),
        migrations.AlterField(
            model_name='auditsection',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audit', verbose_name='Audit'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.audit', verbose_name='Audit'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='question_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditquestionresponse', verbose_name='Question Response'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Section'),
        ),
    ]
