# Generated by Django 5.2.8 on 2025-11-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auditsection_is_completed'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='audit',
            name='core_audit_restaur_115d36_idx',
        ),
        migrations.RemoveIndex(
            model_name='audit',
            name='core_audit_auditor_03082b_idx',
        ),
        migrations.RemoveIndex(
            model_name='audit',
            name='core_audit_grade_c6e841_idx',
        ),
        migrations.RemoveIndex(
            model_name='audit',
            name='core_audit_is_comp_27555f_idx',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='audit',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='auditsection',
            name='is_completed',
        ),
    ]
