# Generated by Django 5.2.8 on 2025-11-24 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_auditsection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.section', verbose_name='Section'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section', 'order'], name='core_questi_section_bef20c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_critical'], name='core_questi_is_crit_6b5f02_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city'], name='core_restau_city_bff963_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['code'], name='core_restau_code_7b743e_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='core_restau_name_aa744f_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['order'], name='core_sectio_order_3cbe58_idx'),
        ),
    ]
