# Generated by Django 5.2.8 on 2025-11-24 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_restaurant_options_alter_question_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='core_questi_section_bef20c_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='core_questi_is_crit_6b5f02_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='core_restau_city_bff963_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='core_restau_code_7b743e_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurant',
            name='core_restau_name_aa744f_idx',
        ),
        migrations.RemoveIndex(
            model_name='section',
            name='core_sectio_order_3cbe58_idx',
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.section', verbose_name='Section'),
        ),
    ]
