# Generated by Django 5.2.8 on 2025-11-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_audit_completed_at_audit_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsection',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
