# Generated by Django 5.2.8 on 2025-11-25 06:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_restaurant_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditsection',
            options={'verbose_name': 'Audit Section', 'verbose_name_plural': 'Audit Sections'},
        ),
        migrations.AlterModelOptions(
            name='correctiveaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Corrective Action', 'verbose_name_plural': 'Corrective Actions'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
        migrations.AlterUniqueTogether(
            name='auditquestionresponse',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='auditsection',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audit_date',
            field=models.DateField(help_text='Date when the audit was conducted', verbose_name='Audit Date'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='auditee_signature',
            field=models.TextField(blank=True, help_text='Digital signature of the auditee', verbose_name='Auditee Signature'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='auditor_signature',
            field=models.TextField(blank=True, help_text='Digital signature of the auditor', verbose_name='Auditor Signature'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='manager_on_duty',
            field=models.CharField(help_text='Name of the manager present during audit', max_length=255, verbose_name='Manager On Duty'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='total_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Percentage'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='total_possible',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Possible Score'),
        ),
        migrations.AlterField(
            model_name='audit',
            name='total_scored',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Score'),
        ),
        migrations.AlterField(
            model_name='auditquestionresponse',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments or observations', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='auditsection',
            name='possible_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Possible Points'),
        ),
        migrations.AlterField(
            model_name='auditsection',
            name='scored_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Scored Points'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='assigned_to',
            field=models.CharField(help_text='Person responsible for completing the action', max_length=255, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='comments',
            field=models.TextField(blank=True, help_text='Additional comments or progress notes', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='deadline',
            field=models.DateField(help_text='Target completion date', verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='correctiveaction',
            name='description',
            field=models.TextField(help_text='Detailed description of the corrective action needed', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='question',
            name='critical_failure_condition',
            field=models.TextField(blank=True, help_text='Description of what constitutes a critical failure', verbose_name='Critical Failure Condition'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_critical',
            field=models.BooleanField(default=False, help_text='Whether this is a critical question (zero score fails entire audit)', verbose_name='Critical?'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order within section', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='question',
            name='possible_points',
            field=models.DecimalField(decimal_places=2, help_text='Maximum points achievable for this question', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Possible Points'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(help_text='The audit question text', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.section', verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(help_text='Street address of the restaurant', max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(help_text='City where the restaurant is located', max_length=100, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='code',
            field=models.CharField(help_text='Unique identifier for the restaurant', max_length=50, unique=True, verbose_name='Restaurant Code'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='country',
            field=models.CharField(default='Pakistan', help_text='Country where the restaurant is located', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(help_text='Official name of the restaurant', max_length=255, verbose_name='Restaurant Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the section', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(help_text='Name of the audit section', max_length=50, verbose_name='Section Name'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order for sections', verbose_name='Order'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['created_at'], name='core_audit_created_8aaf3e_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['submitted_at'], name='core_audit_submitt_135232_idx'),
        ),
        migrations.AddIndex(
            model_name='auditquestionresponse',
            index=models.Index(fields=['audit_section', 'question'], name='core_auditq_audit_s_4103ef_idx'),
        ),
        migrations.AddIndex(
            model_name='auditquestionresponse',
            index=models.Index(fields=['needs_corrective_action'], name='core_auditq_needs_c_c921c3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsection',
            index=models.Index(fields=['audit', 'section'], name='core_audits_audit_i_642485_idx'),
        ),
        migrations.AddIndex(
            model_name='auditsection',
            index=models.Index(fields=['has_critical_failure'], name='core_audits_has_cri_b9149c_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['audit'], name='core_correc_audit_i_7e9ebd_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['risk_level'], name='core_correc_risk_le_20ba95_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['completed'], name='core_correc_complet_5bd521_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['deadline'], name='core_correc_deadlin_af0f09_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['created_at'], name='core_correc_created_171c57_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['section', 'order'], name='core_questi_section_bef20c_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['is_critical'], name='core_questi_is_crit_6b5f02_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city'], name='core_restau_city_bff963_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['country'], name='core_restau_country_ca44e7_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['order'], name='core_sectio_order_3cbe58_idx'),
        ),
        migrations.AddConstraint(
            model_name='audit',
            constraint=models.CheckConstraint(condition=models.Q(('total_percentage__lte', 100)), name='audit_total_percentage_max_100'),
        ),
        migrations.AddConstraint(
            model_name='auditquestionresponse',
            constraint=models.UniqueConstraint(fields=('audit_section', 'question'), name='unique_audit_section_question'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.UniqueConstraint(fields=('audit', 'section'), name='unique_audit_section'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.CheckConstraint(condition=models.Q(('section_percentage__gte', 0)), name='auditsection_percentage_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='auditsection',
            constraint=models.CheckConstraint(condition=models.Q(('section_percentage__lte', 100)), name='auditsection_percentage_max_100'),
        ),
    ]
