# Generated by Django 5.2.8 on 2025-11-06 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Pakistani mobile number, e.g. 0300-1234567', regex='^03\\d{2}-?\\d{7}$')]),
        ),
    ]
